swagger: "2.0"
info:
  description: "Swagger documentation for FES-API."
  version: "1.0.0"
  title: "FES API"

paths:
  /get-workflow-templates:
    post:
      summary: "Get available workflow templates"
      description: ""
      operationId: "getTemplates"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Returns workflow templates"
        required: true
        schema:
          type: object
      responses:
        "200":
          description: "List od the cwl and toil workflows."
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /template-description:
    get:
      parameters: 
        - in: query
          name: workflow-template
          required: true
          schema:
            type: string
            format: uuid
          description: The name of the workflow template
      summary: "Get description for the provided workflow template."
      description: ""
      operationId: "getDescription"
      responses:
        "200":
          description: "Template description"
    post:
      summary: "Set a description for the new workflow"
      description: ""
      operationId: "setTemplate"
      consumes:
        - multipart/form-data
      produces:
      - "application/json"
      parameters:
      - in: formData
        name: workflow-template
        description: ""
        required: true
        schema:
          type: string
          format: uuid
      - in: formData
        name: type
        description: "cwl or toil"
        required: true
        schema:
          type: string 
      - in: formData
        name: description
        description: "description of the workflow"
        required: true
        schema:
          type: string 
      responses:
        "200":
          description: "OK"
    put:
      summary: "Update a description for the existing workflow."
      description: ""
      operationId: "updateTemplate"
      consumes:
        - multipart/form-data
      produces:
      - "application/json"
      parameters:
      - in: formData
        name: workflow-template
        description: ""
        required: true
        schema:
          type: string
          format: uuid
      - in: formData
        name: type
        description: "cwl or toil"
        required: true
        schema:
          type: string 
      - in: formData
        name: description
        description: "description of the workflow"
        required: true
        schema:
          type: string 
      responses:
        "200":
          description: "OK"
    delete:
      summary: "Delete a description for the existing workflow. NOT WORKING."
      description: ""
      operationId: "deleteDescription"
      consumes:
        - multipart/form-data
      produces:
      - "application/json"
      parameters:
      - in: formData
        name: workflow-template
        description: ""
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: "OK"
  /get-workflows:
    get:
      parameters: 
        - in: query
          name: workflow-template
          required: false
          schema:
            type: string
            format: uuid
          description: The name of the workflow template
        - in: query
          name: status
          required: false
          schema:
            type: string
          description: Status od the workflow
        - in: query
          name: userID
          required: false
          schema:
            type: string
          description: ID of the user whose workflow it is
        - in: query
          name: type
          required: false
          schema:
            type: string
          description: Type of the workflow (cwl or toil)
      summary: "Get list of all the created workflows"
      description: ""
      operationId: "getWorkflows"
      responses:
        "200":
          description: "Get workflows"
  /get-workflow-info:
    get:
      parameters: 
        - in: query
          name: GUID
          required: true
          schema:
            type: string
            format: uuid
          description: The guid of the workflow template
      summary: "Get info for the spedified workflow"
      description: ""
      operationId: "getWorkflowInfo"
      responses:
        "200":
          description: "Get workflow info"
  /get-status:
    get:
      parameters: 
        - in: query
          name: GUID
          required: true
          schema:
            type: string
            format: uuid
          description: The name of the workflow template
      summary: "Get status of the workflow"
      description: ""
      operationId: "getStatus"
      responses:
        "200":
          description: "Get workflow status"
  /create-workflow:
    post:
      summary: "Creates a new workflow"
      description: ""
      operationId: "createWorkflow"
      consumes:
        - multipart/form-data
      produces:
      - "application/json"
      parameters:
      - in: formData
        name: workflow-template
        description: ""
        required: true
        schema:
          type: string
          format: uuid
      - in: formData
        name: type
        description: "cwl or toil"
        required: true
        schema:
          type: string
      - in: formData
        name: yaml
        description: "Yaml file for the workflow"
        required: true
        type: file
      - in: formData
        name: input_zip
        description: "Zip file containing all the required input files for the workflow."
        required: true
        type: file
      - in: formData
        name: metadata
        description: "Metadata for the workflow"
        required: false
        schema:
          type: string 
      responses:
        "200":
          description: "OK"
  /run-workflow:
    post:
      parameters: 
        - in: body
          name: GUID
          required: true
          schema:
            type: object
            properties:
              GUID: 
                type: string
          description: The name of the workflow template
      summary: "Run workflow"
      description: ""
      operationId: "runWorkflow"
      responses:
        "200":
          description: "OK"
  /get-results:
    get:
      parameters: 
        - in: query
          name: GUID
          required: true
          schema:
            type: string
            format: uuid
          description: GUID of the workflow
      summary: "Get results of the workflow"
      description: ""
      operationId: "getResults"
      responses:
        "200":
          description: "Get workflow results"
          content:
            application/zip:
              schema:
                type: file
  /get-log:
    get:
      parameters: 
        - in: query
          name: GUID
          required: true
          schema:
            type: string
            format: uuid
          description: GUID of the workflow
      summary: "Get log of the workflow"
      description: ""
      operationId: "getLog"
      responses:
        "200":
          description: "Get workflow log"
          content:
            text/plain:
              schema:
                type: file
  /download-workflow:
    get:
      parameters: 
        - in: query
          name: GUID
          required: true
          schema:
            type: string
            format: uuid
          description: GUID of the workflow
      summary: "Download entire workflow"
      description: ""
      operationId: "getLog"
      responses:
        "200":
          description: "Get workflow log"
          content:
            application/zip:
              schema:
                type: file
  /get-output-metadata:
    get:
      parameters: 
        - in: query
          name: GUID
          required: true
          schema:
            type: string
            format: uuid
          description: GUID of the workflow
      summary: "Get schema of the workflow outputs alognside with download links for each file"
      description: ""
      operationId: "getLog"
      responses:
        "200":
          description: "Get workflow log"
          content:
            application/zip:
              schema:
                type: file
  /get-output-file:
    get:
      parameters: 
        - in: query
          name: GUID
          required: true
          schema:
            type: string
            format: uuid
          description: GUID of the workflow
        - in: query
          name: filepath
          required: true
          schema:
            type: string
          description: Relative path of the file in the workflow output directory
      summary: "Download specific output of the workflow"
      description: ""
      operationId: "getLog"
      responses:
        "200":
          description: "Get workflow log"
          content:
            application/zip:
              schema:
                type: file
  /stop-workflow:
    post:
      consumes:
        - application/json
      parameters: 
        - in: body
          name: GUID
          required: true
          schema:
            type: object
            properties:
              GUID: 
                type: string
          description: The name of the workflow template
      summary: "Stop the workflow"
      description: ""
      operationId: "stopWorkflow"
      responses:
        "200":
          description: "Get workflows"

  /delete-workflow:
    post:
      consumes:
        - application/json
      parameters: 
        - in: body
          name: GUID
          required: true
          schema:
            type: object
            properties:
              GUID: 
                type: string
          description: The name of the workflow template
      summary: "Delete the workflow"
      description: ""
      operationId: "deleteWorkflow"
      responses:
        "200":
          description: "OK"


externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"